services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hireready
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis

volumes:
  pgdata: